yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: pnpm
npmRegistryServer: https://registry.npmjs.org
npmPublishAccess: "public"

packageExtensions:
  "@oclif/core@*":
    dependencies:
      "@types/cli-progress": "^3.11.5"
  "oclif@*":
    dependencies:
      tslib: "*"
